base/urls.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.conf.urls import patterns, url

urlpatterns = patterns('',
  url(r'^$', 'base.views.home'),
)

idril/urls.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('base.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^member/', include('member.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^administration/', include('administration.urls')),
    url(r'^mangopay/', include('mangopay_idril.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^legals/', include('legals.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

handler404 = 'administration.views.error404'
handler403 = 'administration.views.error403'
handler500 = 'administration.views.error500'

member/urls.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.conf.urls import patterns, url

urlpatterns = patterns('',
  url(r'^$', 'member.views.member'),
  url(r'^login/$', 'member.views.login'),
  url(r'^auth/$', 'member.views.auth_view'),
  url(r'^logout/$', 'member.views.logout'),
  url(r'^profile/$', 'member.views.profile'),
  url(r'^register/$', 'member.views.register'),
  url(r'^messages/$', 'member.views.all_messages'),
  url(r'^password_change/$', 'member.views.password_change'),
  url(r'^messages/inbox/$', 'member.views.inbox_messages'),
  url(r'^payments/$', 'member.views.payments'),
  url(r'^messages/inbox/unread/$', 'member.views.inbox_unread_messages'),
  url(r'^messages/sent/$', 'member.views.sent_messages'),
  url(r'^messages/new_message/$', 'member.views.new_message'),
  url(r'^messages/markread/$', 'member.views.markread'),
  url(r'^messages/delete/$', 'member.views.delete'),
  url(r'^(?P<username>\w+)/$', 'member.views.profile_view'),

  url(r'^register/confirm/(?P<activation_key>.+)/$',
      'member.views.register_confirm', name='activation_key',),
  url(r'^delete_account/$', 'member.views.delete_account'),
  
  url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
      {'post_reset_redirect': '/member/password/reset/done/'}, name="password_reset"),
     (r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
     (r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
      'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect': '/member/password/done/'}),
     (r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),
)

payment/urls.py
__author__ = 'morgancollino'

from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^(?P<project_id>[0-9]{1,4})/$', 'payment.views.index', name='index'),
    url(r'^choice/(?P<project_id>[0-9]{1,4})/(?P<gift_id>[-0-9]{1,4})/$', 'payment.views.payment_choice', name='choice'),
    url(r'^choice/$', 'payment.views.payment_choice', name='choice2'),
    url(r'^new$', 'payment.views.payment_cb', name='new'),
    url(r'^new/(?P<project_id>[0-9]{1,4})/(?P<gift_id>[-0-9]{1,4})/$', 'payment.views.payment_cb', name='new'),
    url(r'^list$', 'payment.views.payment_list', name='list'),
    url(r'^mypayments$', 'payment.views.payment_list_user', name='list_user'),
    url(r'^detail/(?P<payment_id>[0-9]{1,4})/$', 'payment.views.payment_detail', name='detail'),
    url(r'^refund/(?P<user_id>[0-9]{1,4})/(?P<payment_id>[0-9]{1,4})/$', 'payment.views.refund', name='refund'),
    url(r'^paypal$', 'payment.views.paypal', name='paypal'),
    url(r'^response$', 'payment.views.response', name='response'),
    url(r'^successfull/(?P<payment>\d+)/$', 'payment.views.successfull', name='successfull'),
    url(r'^paypal/return/(?P<user_id>[0-9]{1,4})/(?P<project_id>[0-9]{1,4})/(?P<gift_id>[-0-9]{1,4})/$', 'payment.views.return_paypal', name='return'),
    url(r'^paypal/cancel/(?P<user_id>[0-9]{1,4})/(?P<project_id>[0-9]{1,4})/(?P<gift_id>[-0-9]{1,4})/$', 'payment.views.cancel_paypal', name='cancel'),
    url(r'^paypal/you/re/not/gonna/find/me/coeur/idril/(?P<user_id>[0-9]{1,4})/(?P<project_id>[0-9]{1,4})/(?P<gift_id>[-0-9]{1,4})/$', 'payment.views.notify_paypal', name='notify'),
    url(r'^paypal/pdt/', include('paypal.standard.pdt.urls')),
)

member/models.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from django.utils.timezone import utc
from django.contrib.auth.models import User
from django.contrib import admin
from mangopay_idril.models import IdrilMangoPayUser, IdrilMangoPayWallet

class Profile(models.Model):
    GENDER = (
        ('0', 'MALE'),
        ('1', 'FEMALE'),
    )
    user = models.OneToOneField(User)
    birth_date = models.DateField(null=True)
    gender = models.CharField(max_length=1, choices=GENDER, default=0,
                              null=True)
    description = models.TextField(null=True)
    supression_date = models.DateField(null=True)
    activation_key = models.CharField(max_length=40, null=True)
    key_expires = models.DateTimeField(null=True)
    avatar = models.FileField(upload_to="avatar/",
                              default='default-avatar.jpeg')  # FK
    gifts = models.ManyToManyField('project.Gift')  # MTM
    achievements = models.ManyToManyField('base.Achievement')  # MTM

    def __unicode__(self):
        return unicode(self.user)

    def create_mangopay(self):
        try:
            mangopay_user = IdrilMangoPayUser.objects.get(user__id=self.user.id)
        except Exception:
            mangopay_user = IdrilMangoPayUser()
            print('USER:')
            print(self.user)
            mangopay_user.create_user(self.user, 'FR', 'FR', self.birth_date)
        try:
            userwallet = IdrilMangoPayWallet.objects.get(user__id=self.user.id)
        except Exception:
            userwallet = IdrilMangoPayWallet()
            userwallet.create_userwallet(mangopay_user, self.user)

User.profile = property(lambda u: Profile.objects.get_or_create(user=u)[0])
User.address = property(lambda u: Address.objects.get_or_create(user=u)[0])


class Address(models.Model):
    street1 = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True)
    zip_code = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    phone_number1 = models.CharField(max_length=20)
    phone_number2 = models.CharField(max_length=20, blank=True)
    user = models.ForeignKey(User)  # FK


class PersonnalInformation(models.Model):
    credit_card_number = models.CharField(max_length=20)
    credit_card_expiration_date = models.DateField()
    user = models.ForeignKey(User)  # FK


class MailMessage(models.Model):
    receiver = models.ForeignKey(User, related_name='mailMessage_receiver')  # FK
    sender = models.ForeignKey(User, related_name='mailMessage_sender')  # FK
    date = models.DateTimeField(null=True, default=datetime.utcnow().replace(tzinfo=utc))
    subject = models.CharField(max_length=50)
    content = models.TextField()    
    read = models.BooleanField(default=False)

admin.site.register(Profile)
admin.site.register(Address)

member/views.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
import datetime
import hashlib
import uuid

from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib import auth
from django.conf import settings
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.core.context_processors import csrf
from django.contrib.sites.models import get_current_site
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.utils.timezone import utc

from member.models import Profile
from models import User
from project.models import Project
from member.models import MailMessage
from member.forms import UserChangeForm
from member.forms import ProfileChangeForm
from member.forms import RegistrationForm
from member.forms import UserPasswordChangeForm
from member.forms import UserAddressForm
from member.forms import NewMessageForm

from payment.models import Payment
from mangopay_idril.models import IdrilMangoPayUser, IdrilMangoPayWallet
from mangopay.client import get_mangopay_api_client
from django.db.models import Q

def get_random_string(string_length=10):
    random = str(uuid.uuid4())  # Convert uuid format to python string.
    random = random.upper()  # Make all characters uppercase.
    random = random.replace("-", "")  # Remove the uuid '-'.
    return random[0:string_length]


def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/member/')
    args = {}
    return render(request, 'member/login.html', args)


@login_required
def member(request):
    args = {}
        # args['user'] = request.user
        # args['new_messages'] = MailMessage.objects.filter(receiver=request.user, read=False).count()
        # args.update(csrf(request))
    return profile(request)


def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    args = {}
    args.update(csrf(request))
    if user is not None:    
        auth.login(request, user)
        profile = None
        try:
            profile = Profile.objects.get(user__id=user.id)
        except Exception as E:
            profile = Profile
            profile.user = user

        try:
            mangopay_userwallet = IdrilMangoPayWallet.get_personal_wallet(request.user.id)
            usermangopay = IdrilMangoPayUser.objects.get(user__id=request.user.id)
        except Exception as e:
            print("Stop here !")
            print(e.message)
            profile.create_mangopay()

        if user.is_active is False:
            args = {}
            args.update(csrf(request))
            args['error'] = True
            args['error_message'] = "Identifiants incorrects"
            return render(request, 'member/login.html', args)
        return HttpResponseRedirect('/member/')
    else:
        args = {}
        args['error'] = True
        args['error_message'] = "Vos identifiants sont incorrects"
        args.update(csrf(request))
        return render(request, 'member/login.html', args)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/member/login')

def profile_view(request, username):
    user = User.objects.get(username=username)

    args = {}
    args['user'] = user
    args.update(csrf(request))
    return render(request, 'member/profile_view.html', args)

@login_required
def profile(request):
    args = {}
    MessageForm = NewMessageForm()
    try:
        wallet = IdrilMangoPayWallet.get_personal_wallet(request.user.id)
        panier = wallet.balance()
        args['Panier'] = panier.amount
        print('Panier: ' + str(panier))
    except BaseException:
        print('No wallet - Connected to the current User :' + str(request.user.id))

    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect('/member/')
        UserForm = UserChangeForm(request.POST, instance=request.user)
        ProfileForm = ProfileChangeForm(request.POST, request.FILES,
                                        instance=request.user.profile)
        AddressForm = UserAddressForm(request.POST,
                                      instance=request.user.address)
        if UserForm.is_valid() and ProfileForm.is_valid() and AddressForm.is_valid():
            print("valid");
            user = UserForm.save()
            profile = ProfileForm.save()
            address = AddressForm.save(commit=False)
            address.user = user
            address.save()
            args['success'] = True
            args['success_message'] = "Votre profil a été correctement\
                                        enregistré."
        else:
            print(UserForm.errors);
            print(ProfileForm.errors);
            print(AddressForm.errors);
    else:
        user = request.user
        UserForm = UserChangeForm(instance=user)
        ProfileForm = ProfileChangeForm(instance=user.profile)
        AddressForm = UserAddressForm(instance=request.user.address)
        MessageForm = NewMessageForm()
    messages = MailMessage.objects.filter(receiver=request.user)
    projects = Project.objects.filter(user=request.user)
    payins = []
    cards = []
    try:
        mangopay_user = IdrilMangoPayUser.objects.filter(user__id=request.user.id)[:1]
        if mangopay_user:
            cards = get_mangopay_api_client().users.GetCards(mangopay_user[0].mangopay_id)
        if mangopay_user:
            payins = Payment.objects.all().filter(Q(user__id__contains=request.user.id)).order_by('-payment_date')
    except Exception as e:
        print(e.message)
    # args['projects'] = projects
    args['Messages'] = messages
    args['UserForm'] = UserForm
    args['ProfileForm'] = ProfileForm
    args['AddressForm'] = AddressForm
    args['NewMessageForm'] = MessageForm
    args['Projects'] = projects
    args['Cards'] = cards
    args['Payins'] = payins
    args.update(csrf(request))
    return render(request, 'member/member.html', args)


@login_required
def password_change(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect('/member/')
        PasswordForm = UserPasswordChangeForm(user=request.user,
                                              data=request.POST)
        if PasswordForm.is_valid():
            PasswordForm.save()
            args = {}
            args['user'] = request.user
            args['PasswordForm'] = PasswordForm
            args['success'] = True
            args['success_message'] = "Votre mot de passe\
                                       a été correctement modifié."
            args.update(csrf(request))
            return render(request, 'member/password_change.html', args)
    else:
        PasswordForm = UserPasswordChangeForm(user=request.user)
    args = {}
    args.update(csrf(request))
    args['PasswordForm'] = PasswordForm
    return render(request, 'member/password_change.html', args)


def send_mail_confirmation(request, user, activation_key):
    current_site = get_current_site(request)
    site_name = current_site.name
    domain = current_site.domain
    c = {
         'user': user,
         'domain': domain,
         'site_name': site_name,
         'protocol': 'http',
         # 'protocol': 'https' if use_https else 'http',
         'activation_key': activation_key,
        }
    subject = 'Confirmez votre compte'
    email = loader.render_to_string("member/register_confirm_email.html", c)
    send_mail(subject, email, settings.EMAIL_HOST_USER, [user.email])


def set_activation_key(profile):
    # Creation activation key
    salt = hashlib.new("sha1")
    salt.update(get_random_string())
    activation_key = hashlib.new("sha1")
    activation_key.update(salt.hexdigest()+profile.user.username)
    # Set to profile
    profile.activation_key = activation_key.hexdigest()
    profile.key_expires = datetime.datetime.now() + datetime.timedelta(hours=6)

def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/member/')
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return HttpResponseRedirect('/member/')
        UserForm = RegistrationForm(request.POST)
        ProfileForm = ProfileChangeForm()
        AddressForm = UserAddressForm()
        if UserForm.is_valid():
            user = UserForm.save()
            profile = ProfileForm.save(commit=False)
            profile.user = user
            set_activation_key(profile)
            profile.save()

            profile.create_mangopay()

            address = AddressForm.save(commit=False)
            address.user = user
            address.save()

            # send_mail_confirmation
            send_mail_confirmation(request, user, profile.activation_key)
            args = {}
            args['success'] = True
            args['success_message'] = "Félicitations vous êtes\
                                       maintenant inscrit ! Veuillez vous rendre sur votre boite mail pour valider votre inscription."
            args.update(csrf(request))
            return render(request, 'member/login.html', args)
        else:
            print UserForm.errors
    else:
        UserForm = RegistrationForm()
    args = {}
    args['UserForm'] = UserForm
    args.update(csrf(request))
    return render(request, 'member/register.html', args)


def register_confirm(request, activation_key):
    args = {}
    profile = get_object_or_404(Profile, activation_key=activation_key)
    if profile is not None:
        if profile.key_expires > datetime.datetime.utcnow().replace(tzinfo=utc) and profile.supression_date is None:
            profile.user.is_active = True
            profile.activation_key = None
            profile.key_expires = None

templates/member/login.html
{% extends "member/member.html" %}
{% load staticfiles %}
{% load sekizai_tags %}

{% block title %}
<title>Espace membre</title>
{% endblock title %}

{% block content %}
<div class="container_12 clearfix">
    <div class="login-form">
    <br>
    <h2>SE CONNECTER</h2>
    <br>
        {% if error == True %}
        <p id="error_msg">{{ error_message }}</p>
        {% elif success == True %}
        <p id="success_msg">{{ success_message }}</p>
        {% endif %}
        <form class="form" action="/member/auth/" method="POST">
            {% csrf_token %}
            <div class="row-item clearfix">
                <input type="text" name="username" placeholder="NOM D'UTILISATEUR" class="txt txt-login" title="Nom d'utilisateur" />
            </div>
            <div class="row-item clearfix">
                <input type="password" name="password" placeholder="MOT DE PASSE" class="txt txt-login" title="Mot de passe" />
            </div>			
            <button class="btn btn-white btn-login" type="submit">Se connecter</button> 
            <br>             
            <a href="/member/password/reset/" class="forgot-pwd">Mot de passe oublié ?</a>
            <div class="already-account">
                <p>Pas encore inscrit ? <a href="/member/register">Cliquez ici</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/member/member.html
{% extends "base/index.html" %}
{% load staticfiles %}

{% block css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static "member/member.css" %}">
    <link rel="stylesheet" href="{% static "member/forms.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "member/css/datepicker/datepicker.css" %}">
{% endblock css %}

{% block script %}
{{ block.super }}
<script src="{% static "member/js/datepicker/bootstrap-datepicker.js" %}"></script>
<script>
    $(function () {
           $('#id_birth_date').datepicker({format: "dd/mm/yyyy", endDate: "+Infinity"});
    });
</script>
{% endblock script %}

{% block content %}
<div class="container_12 clearfix">
    <div class="content grid_12">
        <div class="project-detail">
            <div class="project-tab-detail tabbable accordion">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#"><span class="glyphicon glyphicon-user"></span> Profil</a></li>
                    <li><a href="#" class="be-fc-orange"><span class="glyphicon glyphicon-book"></span> Résumé</a></li>
                    <li><a href="#" class="be-fc-orange"><span class="glyphicon glyphicon-envelope"></span> Messages</a></li>
                    <li><a href="#" class="be-fc-orange"><span class="glyphicon glyphicon-list-alt"></span> Projets</a></li>
                    <li><a href="#" class="be-fc-orange"><span class="glyphicon glyphicon-envelope"></span> Paiements</a></li>
                </ul>
                <div class="tab-content">
                    {% block tab-content %}
                    {% include "member/profile.html" %}
                    {% include "member/resume.html" %}
                    {% include "member/messages.html" %}
                    {% include "member/projects.html" %}
                    {% include "member/payments.html" %}
                    {% include "member/notifications.html" %}
                    {% endblock tab-content %}
                </div>
            </div>
        </div>
    </div>  
<div class="clear"></div>
</div>
{% endblock content %}

templates/member/messages.html
<div>
    <h3 class="rs alternate-tab accordion-label">Inbox</h3>
    <div class="tab-pane accordion-content">
    <div class="form">
        <div class="message-action">
            <a type="button" class="new-message be-fc-orange" data-toggle="modal" data-target="#newMessageModal" data-whatever="">Nouveau message</a>
        </div>
         <div class="alert alert-success message-send-alert" style="margin:15px">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            Votre message a été envoyé.
        </div>
        <div class="box-list-message">
            {% if Messages.count == 0 %}
                <br><p>Aucun message</p>
            {% else %}
                {% for message in Messages %}
                    {% if message.read %}
                        <div class="message-item row">
                    {% else %}
                        <div class="message-item message-unread row">
                    {% endif %}
                            <input type="hidden" class="message-id" value="{{ message.id }}"/>
                            <div class="text-right message-item-action">
                                <button type="button" class="btn delete-message">
                                    <i class="fa fa-trash"></i>
                                </button>
                                <button type="button" class="btn new-message" data-toggle="modal" data-target="#newMessageModal" data-whatever="R">
                                    <i class="fa fa-reply"></i>
                                </button>
                            </div>
                            <div class="col-md-2">
                                <h4 class="rs comment-author">
                                    <a href="#" class="be-fc-orange fw-b username">{{ message.sender.username }}</a>
                                </h4>
                                <img class="avatar-message" src="{{ MEDIA_URL }}/{{ message.sender.profile.avatar }}" alt="$USER_NAME">
                            </div>
                            <div class="col-md-10 text-left">
                                <p class="rs comment-content">{{ message.content|safe }}</p>
                                <p class="rs time-post">Le {{ message.date|date:'d/m/Y' }} à {{ message.date|date:'H:i' }}</p>
                            </div>
                        </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    </div>
</div>

<div class="modal fade message-modal" id="newMessageModal" tabindex="-1" role="dialog" aria-labelledby="newMessageModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fermer</span></button>
            <h4 class="modal-title" id="newMessageModal">Nouveau message</h4>
        </div>
        <form id="send-message" enctype="multipart/form-data" action="/member/messages/new_message/" method="POST">{% csrf_token %}
            <div class="modal-body">
                  <div class="form-group text-left">
                    <label for="recipient-name" class="label-profile">Destinataire</label>
                    {{ NewMessageForm.receiver }}
                  </div>
                  <div class="form-group text-left">
                    <label for="message-text" class="label-profile">Message</label>
                    {{ NewMessageForm.content }}
                  </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-black" data-dismiss="modal">Fermer</button>
                <input type="submit" class="btn btn-white" value="Envoyer"/>
            </div>
      </form>
    </div>
  </div>
</div>

<script type="text/javascript"> 
$( document ).ready(function()
{
    $('.message-item').css("margin-left", 0).css("margin-right", 0);
    $('.message-send-alert').hide();

    var receivers = [];
    $("#id_receiver").find('option').each(function()
    {
        receivers.push($(this).text());

    });
    console.log(receivers);

    $('.new-message').click(function()
    {
        $('.message-modal').find('.form-control').val('');
    });

    $("#id_receiver").autocomplete(
    {
        source:receivers
    });

    $('#send-message').submit(function()
    {
        var success = false;
        $.ajax(
        {
            data: $(this).serialize(), 
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            async:false,
            success: function(response)
            { 
                success=true;
            }
        });
        if (success)
        {
            $('.message-modal').modal('toggle');
            $('.message-send-alert').show();
            $('.message-send-alert').show(0).delay(5000).hide(0);
        }
        return false;
    });

    $('.message-unread').click(function()
    {
        var messageId = $(this).find('.message-id').val();
        var success = false;
        $.ajax(
        {
            data : {csrfmiddlewaretoken: '{{ csrf_token }}', 'messageId': messageId},
            type: 'POST',
            url: '/member/messages/markread/',
            async: false,
            success: function(response)
            {
                if (response == 'OK')
                    success = true;
            },
            error: function(response, statut, erreur)
            {
                alert(response);
            }
        });
        if (success)
        {
            $(this).find('.new-message-alert').remove();
            $(this).removeClass("message-unread");
            $(this).unbind('click');
        }
    });

    $('.delete-message').click(function()
    {
        var messageId = $(this).parents().eq(1).find('.message-id').val();
        var success = false;
        $.ajax(
        {
            data : {csrfmiddlewaretoken: '{{ csrf_token }}', 'messageId': messageId},
            type: 'POST',
            url: '/member/messages/delete/',
            async: false,
            success: function(response)
            {
                if (response == 'OK')
                   success = true;
            },
            error: function(response, statut, erreur)
            {
            }
        });
        if (success)
            $(this).parents().eq(1).remove();
    });

    $('#id_receiver').selectize(
    {
    });
});
</script>

templates/member/new_message.html
{% extends "member/member.html" %}
{% load staticfiles %}

{% block title %}
<title>Nouveau message</title>
{% endblock title %}

{% block css %}
{{ block.super}}
<link rel="stylesheet" href="{% static "member/messages.css" %}">
{% endblock css %}

{% block script %}
{% endblock script %}

{% block content %}
<div class="container_12 clearfix">
    <div class="panel panel-default" style="padding-top: 20px">
		<form enctype="multipart/form-data" action="/member/messages/new_message/" method="POST">{% csrf_token %}
	        <div class="modal-body">
		        <div class="form-group text-left">
		        	<label class="label-message" style="margin-right: 10px">Destinataire</label><b>{{ to }}</b>
                    <input type="hidden" id="id_receiver" name="id_receiver" value="{{ to }}"/>
		        </div>
		        <div class="form-group text-left">
		            <label class="label-message" style="margin-bottom:10px">Votre message</label>
					{{ newMessageForm.content }}
					{{ newMessageForm.content.errors }}
		        </div>
        	</div>
	       <div class="row" style="margin-bottom: 20px">
				<div class="col-md-3 col-md-offset-9">
					<button class="btn btn-white" type="submit" name="cancel">Retour</button>
					<button class="btn btn-white" type="submit" name="save">Envoyer</button>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/member/notifications.html
 <div>
        <h3 class="rs alternate-tab accordion-label">Notifications</h3>
        <div class="tab-pane accordion-content">
            <br/> Notifications<br/> <br/> <br/> <br/><br/><br/>
        </div>
</div>

templates/member/password_change.html
{% extends "member/member.html" %}
{% load staticfiles %}

{% block content %}
<div class="container_12 clearfix start-project">
    <div class="panel panel-default" style="padding-top: 20px">
		<form class="form" enctype="multipart/form-data" action="/member/password_change/" method="POST">{% csrf_token %}
			{% if success == True %}
			<div class="row-item clearfix">
				<p id="success_msg">{{ success_message }}</p>
			</div>
			{% endif %}

			<div class="row-item clearfix">
                <div class="col-md-4 text-right">
                    <label class="label-profile">Ancien mot de passe</label><span class="mandatory-field">*</span>
                </div>
            	
                <div class="col-md-8 text-left">
					{{ PasswordForm.old_password }}
                    <div class="col-md-8 text-center">
						{{ PasswordForm.old_password.errors }}
                    </div>
                </div>
            </div>

			<div class="row-item clearfix">
                <div class="col-md-4 text-right">
                    <label class="label-profile">Nouveau mot de passe</label><span class="mandatory-field">*</span>
                </div>
            	
                <div class="col-md-8 text-left">
					{{ PasswordForm.new_password1 }}
                    <div class="col-md-8 text-center">
						{{ PasswordForm.new_password1.errors }}
                    </div>
                </div>
            </div>
            
            <div class="row-item clearfix">
                <div class="col-md-4 text-right">
                    <label class="label-profile">Mot de passe vérification</label><span class="mandatory-field">*</span>
                </div>
            	
                <div class="col-md-8 text-left">
					{{ PasswordForm.new_password2 }}
                    <div class="col-md-8 text-center">
						{{ PasswordForm.new_password2.errors }}
                    </div>
                </div>
            </div>

			<div class="row-item clearfix">
				<button class="btn btn-white" type="submit" name="cancel">Retour</button>
				<button class="btn btn-white" type="submit" name="save">Sauvegarder</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}