base/urls.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.conf.urls import patterns, url

urlpatterns = patterns('',
  url(r'^$', 'base.views.home'),
)

idril/urls.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('base.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^member/', include('member.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^administration/', include('administration.urls')),
    url(r'^mangopay/', include('mangopay_idril.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^legals/', include('legals.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

handler404 = 'administration.views.error404'
handler403 = 'administration.views.error403'
handler500 = 'administration.views.error500'

project/urls.py
from django.conf.urls import patterns, url

# URL planning a voir, juste prototype pour le moment.
urlpatterns = patterns('',
  url(r'^$', 'project.views.home'),
  url(r'^project_(?P<id>\d+)/$', 'project.views.details'),
  url(r'^project_(?P<id>\d+)/edit/$', 'project.views.edit'),
  url(r'^create/$', 'project.views.create'),
  url(r'^category/(?P<category_id>[0-9]{1,4})/$', 'project.views.list_category'),
  url(r'^search$', 'project.views.list_projects'),
  url(r'^project_(?P<id>\d+)/add_comment/$', 'project.views.add_comment'),
)

member/models.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from django.utils.timezone import utc
from django.contrib.auth.models import User
from django.contrib import admin
from mangopay_idril.models import IdrilMangoPayUser, IdrilMangoPayWallet

class Profile(models.Model):
    GENDER = (
        ('0', 'MALE'),
        ('1', 'FEMALE'),
    )
    user = models.OneToOneField(User)
    birth_date = models.DateField(null=True)
    gender = models.CharField(max_length=1, choices=GENDER, default=0,
                              null=True)
    description = models.TextField(null=True)
    supression_date = models.DateField(null=True)
    activation_key = models.CharField(max_length=40, null=True)
    key_expires = models.DateTimeField(null=True)
    avatar = models.FileField(upload_to="avatar/",
                              default='default-avatar.jpeg')  # FK
    gifts = models.ManyToManyField('project.Gift')  # MTM
    achievements = models.ManyToManyField('base.Achievement')  # MTM

    def __unicode__(self):
        return unicode(self.user)

    def create_mangopay(self):
        try:
            mangopay_user = IdrilMangoPayUser.objects.get(user__id=self.user.id)
        except Exception:
            mangopay_user = IdrilMangoPayUser()
            print('USER:')
            print(self.user)
            mangopay_user.create_user(self.user, 'FR', 'FR', self.birth_date)
        try:
            userwallet = IdrilMangoPayWallet.objects.get(user__id=self.user.id)
        except Exception:
            userwallet = IdrilMangoPayWallet()
            userwallet.create_userwallet(mangopay_user, self.user)

User.profile = property(lambda u: Profile.objects.get_or_create(user=u)[0])
User.address = property(lambda u: Address.objects.get_or_create(user=u)[0])


class Address(models.Model):
    street1 = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True)
    zip_code = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    phone_number1 = models.CharField(max_length=20)
    phone_number2 = models.CharField(max_length=20, blank=True)
    user = models.ForeignKey(User)  # FK


class PersonnalInformation(models.Model):
    credit_card_number = models.CharField(max_length=20)
    credit_card_expiration_date = models.DateField()
    user = models.ForeignKey(User)  # FK


class MailMessage(models.Model):
    receiver = models.ForeignKey(User, related_name='mailMessage_receiver')  # FK
    sender = models.ForeignKey(User, related_name='mailMessage_sender')  # FK
    date = models.DateTimeField(null=True, default=datetime.utcnow().replace(tzinfo=utc))
    subject = models.CharField(max_length=50)
    content = models.TextField()    
    read = models.BooleanField(default=False)

admin.site.register(Profile)
admin.site.register(Address)

project/models.py
# -*- coding: utf8 -*-

'''
Voir le formset wizard pour faire la creation de projets en
plusieurs etapes.
1 - Nom du projet, contenu ;
2 - Gifts.

'''

from __future__ import unicode_literals
from django.db import models
from base.models import Media, Permission
# from member.models import Profile
from django.db import models
from django.forms import ModelForm
from datetime import date
from django.db.models import get_model # Erreur de double inclusion si import de payment.models -> Payment
from member.models import User
import datetime



class Gift(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    amount_required = models.DecimalField(max_digits=15, decimal_places=2)
    max_amount = models.IntegerField(null=True, default=None, blank=True)

    def __str__(self):
        return self.name

class ProjectCategory(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()

class Project(models.Model):
    STATECHOICE = (
        ('0', 'CANCELED'),
        ('1', 'IN PROGRESS'),
        ('2', 'FUNDED'),
        ('3', 'FAILED'),
        ('4', 'WAITING VALIDATION'),
    )
    user = models.ForeignKey(User) # Project's creator
    title = models.CharField(max_length=50, null=True)
    short_description = models.CharField(max_length=255, null=True)
    content = models.TextField(null=True)
    date = models.DateField(null=True, default=date.today())
    date_modified = models.DateField(null=True)
    end_date = models.DateField(null=True)
    amount_required = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    amount_actual = models.DecimalField(max_digits=15, decimal_places=2, null=True, default=0)
    state = models.CharField(max_length=1, choices=STATECHOICE, default=1, null=True)
    # medias = models.ManyToManyField(Media, null=True)
    header = models.FileField(upload_to="project/headers", null=True)
    permission = models.ForeignKey(Permission, null=True)
    category = models.ForeignKey(ProjectCategory, null=True)
    gifts = models.ManyToManyField(Gift, null=True, default=None, blank=True)

    def __str__(self):
        return self.title

    def get_funds_for_project(self):
        payment = get_model('payment', 'Payment')
        payment_list = payment.objects.all().filter(project__id=self.id, payment_status='PAID')
        amount = 0
        for payment in payment_list:
            amount += payment.price

        return amount

    def get_nb_gift_for_project(self, gift_id):
        payment = get_model('payment', 'Payment')
        count = payment.objects.all().filter(project__id=self.id,
                                                    payment_status='PAID',
                                                    gift__id=gift_id).count()
        if __debug__:
            print('--> Count for gift_id='+str(gift_id) + ': ' + str(count))
        return count

    def get_percentage(self):
        amount = self.get_funds_for_project()
        percent = (amount / self.amount_required) * 100
        percent = "%.1f" % percent
        return percent

    def get_days_left(self):
        _date = datetime.date.today()
        days = (self.end_date-_date).days
        return days

    def days_left(self):
        d1 = datetime.datetime.utcnow()
        d2 = self.end_date
        return abs((d2 - d1).days)

    def stop(self):
        self.state = '0'
        self.save()

    def is_in_progress(self):
        return self.state == '1'
    def is_cancelled(self):
        return self.state == '0'


class Funding(models.Model):
    date = models.DateField()
    amount = models.DecimalField(max_digits=50, decimal_places=2)
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    gift = models.ForeignKey(Gift, null=True, default=None)

class ProjectComment(models.Model):
    content = models.TextField()
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)
    date = models.DateField(default=date.today())

project/views.py
# -*- coding: utf8 -*-

from __future__ import unicode_literals
from datetime import date
import operator

from django.http import HttpResponseRedirect
from django.shortcuts import render
import bleach

from django.contrib.auth.decorators import login_required
from django.core.exceptions import *

from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from member.models import Address

from project.models import Project
from project.models import ProjectComment
from project.models import Gift
from project.models import ProjectCategory
from project.forms import ProjectFormEdit
from project.forms import ProjectFormCreate
from project.forms import GiftFormSetCreate
from project.forms import AddCommentForm
from mangopay_idril.models import IdrilMangoPayWallet, IdrilMangoPayUser


def home(request):
    #ordered = sorted(projects, key=operator.attrgetter('category.name')) # Plus rapide que de faire
    amount = 0                                                                     # un in a chaque fois dans la boucle plus bas pour verifier si une clef existe ?
    categories = ProjectCategory.objects.all()
    selected_category = categories.first()
    print request.POST
    if request.method == 'POST':
        post = request.POST
        if 'selected_category' in post:
            try:
                selected_category = ProjectCategory.objects.all().get(name=post.get('selected_category'))
            except:
                selected_category = categories.first()
    if selected_category is None:
        nb_project_category = 0
        projects = None
    else:
        nb_project_category = Project.objects.all().filter(category__id=selected_category.id).filter(state='1').count()
        projects = Project.objects.all().filter(category__id=selected_category.id).filter(state__in=['1', '2', '3']).order_by('-date')[:3]
    return render(request, 'project/project_view.html', {'projects': projects, 'project_amount': amount
                        ,'categories': categories, 'selected_category': selected_category,
                                                         'nb_project_category': nb_project_category})


def details(request, id):
    project = get_object_or_404(Project, id=id)
    if request.user.is_staff == False and project.state == '4':
        return redirect('/project')
    comments = ProjectComment.objects.filter(project = project)
    amount = project.get_funds_for_project()
    percent = (amount / project.amount_required) * 100
    percent = "%.2f" % percent
    days = (project.end_date-project.date).days
    isCreator = project.user.id == request.user.id or request.user.is_staff == 1
    comment_form = AddCommentForm(prefix='comment')
    return render(request, 'project/project_details.html',
                  {'project': project, 'percent': percent, 'amount': amount,
                   'days': days, 'isCreator': isCreator, 'comments': comments, 'comment_form': comment_form})

@login_required
def edit(request, id):
    project = Project.objects.get(id=id)
    if request.method == 'POST':
        form = ProjectFormEdit(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project.date_modified = date.today()
            form.save()
            return HttpResponseRedirect('/project/project_' + str(project.id))
    else:
        form = ProjectFormEdit(instance=project)
    return render(request, 'project/project_edit.html',
                  {'project': project, 'form': form})

@login_required
def create(request):
    # A user must have some info set to create a project
    user = request.user
    try:
        user_address = Address.objects.get(user=user)
    except Exception:
        user_address = None
    if not user.first_name or not user.last_name or not user.email \
       or not user_address.street1 or not user_address.zip_code \
       or not user_address.city or not user_address.phone_number1:
        return render(request, 'project/project_more_info.html')

    categories = ProjectCategory.objects.all()
    if request.method == 'POST':
        project_form = ProjectFormCreate(request.POST, request.FILES, prefix='project')
        gift_formset = GiftFormSetCreate(request.POST, prefix='gift')
        if project_form.is_valid() and gift_formset.is_valid():
            project = project_form.save(commit=False)
            project.user = request.user
            # project.content = bleach.clean(project.content, tags=('div', 'p', 'strong', 'em', 'span', 'ul', 'li'),
            #                                                 attributes={
            #                                                 '*': ['class', 'style'],
            #                                                 'a': ['href', 'rel'],
            #                                                 'img': ['src', 'alt'],
            #                                                 }) # Cleans HTML. Have to look further for efficiency...

            gifts = gift_formset.save()
            project.state = '4'
            project.save()
            project.gifts = gifts
            project.save()

            # Creation d'un porte-feuille pour le projet - 1 wallet/projet
            try:
                user = IdrilMangoPayUser.objects.get(user__id=request.user.id)
                wallet = IdrilMangoPayWallet()
                wallet.create_wallet(user, project)
            except Exception as e:
                user = 0
                print(e)
            return HttpResponseRedirect('/project')
    else:
        project_form = ProjectFormCreate(prefix='project')
        gift_formset = GiftFormSetCreate(prefix='gift', queryset=Gift.objects.none())
    return render(request, 'project/project_create.html',
                  {'project_form': project_form, 'categories': categories,
                   'gift_formset': gift_formset})

def list_category(request, category_id):
    category = ProjectCategory.objects.all().get(id=category_id)
    projects = Project.objects.all().filter(category__id=category.id).filter(state='1').order_by('-date')
    return render(request, 'project/project_list.html', {'projects': projects, 'category': category})


def list_projects(request):
    projects = list()
    search = ''
    if request.method == 'GET':
        get = request.GET
        if 's' in get:
            projects = Project.objects.all().filter(title__icontains=get.get('s')).filter(state__in=['1', '2', '3']).order_by('-date')
            search = get.get('s')
    return render(request, 'project/project_search.html', {'projects': projects, 'search': search })

@login_required
def add_comment(request, id):
    if request.method == 'POST':
        project = get_object_or_404(Project, id=id)
        comment_form = AddCommentForm(request.POST, prefix='comment')
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.project = project
            comment.save()
            return redirect('/project/project_'+id)
    return redirect('/project/project_'+id)

templates/project/project_create.html
{% extends "base/index.html" %}
{% load staticfiles %}
{% load sekizai_tags %}

{% block head_extra %}
    {# {% load url from future %} #}
    {#<script src="{% url "tinymce-js" "project" %}"></script> {# Oblige de faire comme cela pour load proprement la config tinymce. Par la classe Media dans le forms.py ca ne fonctionne pas proprement (oblige de mettre une URL absolue).#}
    <script src="/static/project/js/tinymce/tinymce.min.js"></script>
    <script src="/static/project/js/datepicker/bootstrap-datepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/project/css/datepicker/datepicker.css">
{% endblock head_extra %}

{% block title %}
    <title>Projets</title>
{% endblock title %}

{% block content %}
    <script>
        $(function () {
            manage_gift.get_base();
            manage_gift.dom_highest = document.getElementById("gifts");

            var today = new Date();
            var sevendays = new Date(today);
            var ninetydays = new Date(today);
            sevendays.setDate(today.getDate()+7);
            ninetydays.setDate(today.getDate()+90);
            $('#id_project-end_date').datepicker({format: 'dd/mm/yyyy', startDate: sevendays, endDate: ninetydays});
        });
        tinymce.init({
            selector: '#id_project-content',
        });
    </script>

    <div class="container_12 clearfix start-project">
        
        <label class="step-title">ETAPE 1</label><label class="step-detail">- Le Projet</label>
        <form action="" method="post" class="form form-start-project" enctype="multipart/form-data" >{% csrf_token %}
            <div class="project-description">
                {{ project_form.non_field_errors }}
                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">TITRE</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-9 text-left">
                            {{ project_form.title }}
                        <div class="col-md-8 text-center">
                            {{ project_form.title.errors }}
                        </div>
                    </div>
                </div>
            
                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">DESCRIPTION COURTE</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-9 text-left">
                        {{ project_form.short_description }}
                        <div class="col-md-8 text-center">
                            {{ project_form.short_description.errors }}
                        </div>
                    </div>
                </div>

                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">DESCRIPTION</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-9 text-left">
                       {{ project_form.content }}
                        <div class="col-md-8 text-center">
                            {{ project_form.content.errors }}
                        </div>
                    </div>
                </div>

                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">IMAGE D'EN TETE</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-3 text-left">
                        <div class="btn btn-white upload-button">
                            <span>Ajouter une image</span>
                        </div>
                       {{ project_form.header }}
                        <div class="col-md-8 text-center">
                            {{ project_form.header.errors }}
                        </div>
                    </div>
                    <div class="col-md-7 text-left">
                            <img id="project-img" src="" alt="" width="200" height="150" />
                            <a id="delete-project-img" href="#" style="display:none;">Supprimer</a>
                    </div>
                    <div>
                        <img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" id="projectImg">
                    </div>
                </div>

                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">MONTANT REQUIS</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-9 text-left">
                       {{ project_form.amount_required }}
                        <div class="col-md-8 text-center">
                            {{ project_form.amount_required.errors }}
                        </div>
                    </div>
                </div>

                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">CATEGORIE</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-9 text-left">
                       <select id="id_project-category" name="project-category">
                            <option value="" selected="selected">----</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-md-8 text-center">
                            {{ project_form.category.errors }}
                        </div>
                    </div>
                </div>
            
                <div class="row-item clearfix">
                    <div class="col-md-2 text-right">
                        <label class="label-project" for="txt_last_name">DATE DE FIN</label><span class="mandatory-field">*</span>
                    </div>
                    <div class="col-md-9 text-left">
                       {{ project_form.end_date }}
                        <span class="help-block">Un projet peut durer au minimum 7 jours, et au maximum 90 jours.</span>
                        <div class="col-md-8 text-center">
                            {{ project_form.end_date.errors }}
                        </div>
                    </div>
                </div>
            </div>

            <label class="step-title">ETAPE 2</label><label class="step-detail">- Les Contreparties </label>
            <div class="gifts form form-start-project">
            <span id="gifts">
                {{ gift_formset.management_form }}

                {% for gift_form in gift_formset.forms %}
                <section id="wrap-gift-0">
                    <div class="row-item clearfix">
                        <div class="col-md-2 text-right">
                            <label for="id_gift-0-name" class="label-project">INTITULÉ</label><span class="mandatory-field">*</span>
                        </div>
                        <div class="col-md-9 text-left">
                            {{ gift_form.name }}
                        </div>
                    </div>
                    <div class="row-item clearfix">
                        <div class="col-md-2 text-right">
                            <label for="id_gift-0-description" class="label-project">DESCRIPTION</label><span class="mandatory-field">*</span>
                        </div>
                        <div class="col-md-9 text-left">
                            {{ gift_form.description }}
                        </div>
                    </div>
                    <div class="row-item clearfix">
                        <div class="col-md-2 text-right">
                            <label for="id_gift-0-amount_required" class="label-project">PRIX</label><span class="mandatory-field">*</span>
                        </div>
                        <div class="col-md-9 text-left">
                            {{ gift_form.amount_required }}
                        </div>
                    </div>
                    <div class="row-item clearfix">
                        <div class="col-md-2 text-right">
                            <label for="id_gift-0-max_amount" class="label-project">ÉLÉMENTS DISPO.</label>
                        </div>
                        <div class="col-md-9 text-left">
                            {{ gift_form.max_amount }}
                            <span class="help-block">Laisser vide si il n'y a pas de limites.</span>
                        </div>
                    </div>
                    <a href="javascript:void(0)" class="btn btn-white" id="delete-{{ gift_form.prefix }}" onclick="manage_gift.delete_gift(this)">Supprimer</a>
                    <hr>
                </section>
                {% endfor %}
            </span>
                 <div class="row" style="padding-bottom:7px">
                    <a id="add-gift" class="btn btn-green" onclick="manage_gift.add_gift(this)">Ajouter un cadeau</a>
                </div>
            </div>
            <div class="row" style="padding-bottom:20px; padding-top:20px">
                <button type="submit" class="btn btn-white">Soumettre le projet</button>
            </div>
        </form>
    </div>


<script>
function readURL(input)
{
    if (input.files && input.files[0])
    {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#projectImg').attr('style', 'max-width:400px; max-height:200px; width:auto; height:auto;');
            $('#projectImg').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#inputProjectImg").change(function() {
    readURL(this);
});


a = null;
var manage_gift = 
{
    dom_highest: null,
    base: null,
    gifts: [],
    add_gift: function()
    {
        var last_elem = document.getElementById("wrap-gift-" + (this.get_total() - 1)); // -1 because index starts at 0.
        var new_elem = this.base.cloneNode(true);
        var total = this.get_total();

        new_elem.innerHTML = this.base.innerHTML.replace(/gift-0/g, "gift-" + total); // No -1 because it is the new one.
        if (last_elem === null) // We have no gifts.
            last_elem = this.dom_highest;
        last_elem.parentNode.insertBefore(new_elem, last_elem.nextSibling);
        // We can't access outerHTML before inserting.
        // We need to replace the outer to replace the span element.
        new_elem.outerHTML = new_elem.outerHTML.replace(/gift-0/, "gift-" + total);
        $('#delete-gift-' + (this.get_total() - 1)).hide(); // We can just delete the last gift, browser limitation. If we delete one gift ine the middle of others, the browser empties all fields of the gifts below the deleted one.
        this.update_total(true);
        this.gifts.push(last_elem.nextSibling);

        return false;
    },
    delete_gift: function(e)
    {
        for (var i = this.gifts.length; i--;) // Remove gift from "gifts" array.
            if(this.gifts[i] === e.parentNode)
                this.gifts.splice(i, 1);
        e.parentNode.remove();
        this.update_total(false);
        this.update_indexes();
        $('#delete-gift-' + (this.get_total() - 1)).show(); // We can just delete the last gift, browser limitation. If we delete one gift ine the middle of others, the browser empties all fields of the gifts below the deleted one.

        return false;
    },
    // Indexes must be contiguous (gift-0, gift-1, etc...), if not, gift will not be saved.
    update_indexes: function()
    {
        for (var i = 0, l = this.gifts.length; i < l; ++i)
            if (this.gifts[i].id !== "wrap-gift-" + i)
            {
                this.gifts[i].id = "wrap-gift-" + i;
                this.gifts[i].innerHTML = this.gifts[i].innerHTML.replace(/(gift-[0-9]+)-/g, "gift-" + i + "-");
            }
    },
    get_base: function()
    {
        var first_gift = document.getElementById("wrap-gift-0");

        this.gifts.push(first_gift);
        this.base = first_gift.cloneNode(true);
    },
    get_total: function()
    {
        return document.getElementById("id_gift-TOTAL_FORMS").value;
    },
    update_total: function(add)
    {
        var elem = document.getElementById("id_gift-TOTAL_FORMS");

        elem.value = parseInt(elem.value) + (add == true ? 1 : -1);
    },
};

$('.upload-button').click(function()
{
    $('#inputProjectImg').trigger('click');
});

function readURL(input)
{
    if (input.files && input.files[0])
    {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#project-img').attr('src', e.target.result);
            $("#delete-project-img").show();
        }

        reader.readAsDataURL(input.files[0]);
    }
}
$("#inputProjectImg").change(function()
{
    readURL(this);
});

$("#delete-project-img").click(function(event)
{
    $('#project-img').attr('src', '');
    $(this).hide();
});
</script>
{% endblock content %}

templates/project/project_create_wizard.html
{% extends "base/index.html" %}
{% load staticfiles %}
{% load sekizai_tags %}

{% block head_extra %}
	{{ wizard.form.media }}
    {% load url from future %}
    <script src="{% url "tinymce-js" "project" %}"></script> {# Oblige de faire comme cela pour load proprement la config tinymce. Par la classe Media dans le forms.py ca ne fonctionne pas proprement (oblige de mettre une URL absolue).#}
{% endblock head_extra %}

{% block title %}
    <title>Projets</title>
{% endblock title %}

{% block content %}
    <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
    <form action="" method="post">{% csrf_token %}
		{{ wizard.management_form }}
		{% if wizard.form.forms %}
		    {{ wizard.form.management_form }}
		    {% for form in wizard.form.forms %}
		        {{ form }}
		    {% endfor %}
		{% else %}
		    {{ wizard.form }}
		{% endif %}
{% endblock content %}

templates/project/project_more_info.html
{% extends "base/index.html" %}
{% load staticfiles %}
{% load sekizai_tags %}

{% block title %}
    <title>Projets</title>
{% endblock title %}

{% block content %}
    <div class="container_12 clearfix">
        <div class="create_required">
            <p>Afin de créer un projet, merci de <a href="{% url 'member.views.member' %}">compléter votre profil</a>.</p>
        </div>
    </div>

{% endblock content %}